version: '3.8'

services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dog-api-tests
    volumes:
      # Monta os resultados dos testes para o host
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
      - ./allure-results:/app/allure-results
      - ./ctrf:/app/ctrf
    environment:
      - CI=true
    # Comando pode ser sobrescrito ao executar
    command: npm test

